#!/usr/bin/env bash
# Apply the Fleet identity (blue bee on navy) to local builds, without
# touching upstream assets.
#
#   desktop: desktop/src-tauri/icons-fleet/ is the icon set; pass it to the
#            demo build as bundle.icon (see desktop-demo-build-fleet).
#   android: writes a src/debug/res overlay that Gradle merges over
#            src/main/res for debug builds only, so a Fleet debug APK gets the
#            blue launcher icon while release builds and upstream assets are
#            untouched.
#
# Source of truth is icons-fleet/icon-1024.png. Requires macOS sips.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/desktop/src-tauri/icons-fleet/icon-1024.png"
NAVY="0A2844"
OUT="$ROOT/mobile/android/app/src/debug/res"
[[ -f "$SRC" ]] || { echo "missing $SRC" >&2; exit 1; }

mkdir -p "$OUT/values"
cat > "$OUT/values/ic_launcher_background.xml" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <!-- Fleet build: navy behind the blue bee. Generated by scripts/fleet-branding.sh -->
  <color name="ic_launcher_background">#${NAVY}</color>
</resources>
EOF

# density: launcher px, foreground px
for spec in mdpi:48:108 hdpi:72:162 xhdpi:96:216 xxhdpi:144:324 xxxhdpi:192:432; do
  IFS=: read -r density launcher fg <<<"$spec"
  dir="$OUT/mipmap-$density"; mkdir -p "$dir"
  sips -s format png --resampleHeightWidth "$launcher" "$launcher" "$SRC" --out "$dir/ic_launcher.png" >/dev/null
  cp "$dir/ic_launcher.png" "$dir/ic_launcher_round.png"
  inner=$(( fg * 8 / 10 ))
  sips -s format png --resampleHeightWidth "$inner" "$inner" "$SRC" --out "$dir/ic_launcher_foreground.png" >/dev/null
  sips --padToHeightWidth "$fg" "$fg" --padColor "$NAVY" "$dir/ic_launcher_foreground.png" >/dev/null
done
echo "fleet branding: android debug overlay written to ${OUT#$ROOT/}"
