import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";

// Generated by the actual read-only Hermes bridge/observer/journal producers.
const canonicalFixture = JSON.parse(
  readFileSync(
    new URL(
      "../../../../../test-fixtures/hermes-attachment/canonical-v1.json",
      import.meta.url,
    ),
    "utf8",
  ),
);

test("actual Hermes-produced multipart replay reaches the production UI reducer atomically", () => {
  assert.equal(
    canonicalFixture.initialize.agentCapabilities._meta.hermesAttachment
      .version,
    1,
  );
  assert.equal(canonicalFixture.load._meta.replayComplete, true);
  const events = canonicalFixture.frames.map((payload, seq) => ({
    ...base,
    seq,
    payload,
  }));
  const expected = canonicalFixture.frames
    .filter((f) => f.params._meta?.kind === "final")
    .map((f) => f.params.update.content.text)
    .join("");
  let state = createEmptyTranscriptState();
  for (const event of events) {
    state = processTranscriptEvent(state, event);
    const meta = event.payload.params._meta;
    if (meta.kind === "final" && meta.part < meta.parts - 1)
      assert.equal(state.items.filter((x) => x.type === "message").length, 0);
  }
  assert.deepEqual(
    state.items.filter((x) => x.type === "message").map((x) => x.text),
    [expected],
  );
  assert.equal(
    state.items.filter((x) => x.title === "Turn completed").length,
    1,
  );
  assert.deepEqual(
    buildTranscript([
      ...events,
      ...events.map((e) => ({ ...e, seq: e.seq + events.length })),
    ]),
    state.items,
  );
});
import {
  buildTranscript,
  createEmptyTranscriptState,
  processTranscriptEvent,
} from "./agentSessionTranscript.ts";

function receipt(seq, params) {
  return {
    ...base,
    seq,
    payload: {
      jsonrpc: "2.0",
      method: "_hermes/turn_complete",
      params: {
        sessionId: "session",
        turnId: "canonical-turn",
        _meta: { deliveryId: 22 },
        ...params,
      },
    },
  };
}

const base = {
  timestamp: "2026-09-26T00:00:00Z",
  kind: "acp_read",
  agentIndex: 0,
  channelId: "channel",
  sessionId: "session",
  turnId: "buzz-turn",
};
function text(seq, text, meta = {}) {
  return {
    ...base,
    seq,
    payload: {
      jsonrpc: "2.0",
      method: "session/update",
      params: {
        sessionId: "session",
        _meta: {
          turnId: "canonical-turn",
          messageId: "canonical-turn:assistant",
          kind: "live",
          operation: "append",
          ...meta,
        },
        update: {
          sessionUpdate: "agent_message_chunk",
          content: { type: "text", text },
        },
      },
    },
  };
}

test("Hermes replacement parts stage atomically and replace live text by stable identity", () => {
  let state = processTranscriptEvent(
    createEmptyTranscriptState(),
    text(1, "Commentary"),
  );
  const first = text(2, "Final ", {
    kind: "final",
    operation: "replace",
    part: 0,
    parts: 2,
    deliveryId: 17,
  });
  const last = text(3, "answer", {
    kind: "final",
    operation: "replace",
    part: 1,
    parts: 2,
    deliveryId: 21,
  });
  state = processTranscriptEvent(state, first);
  assert.deepEqual(
    state.items.filter((x) => x.type === "message").map((x) => x.text),
    ["Commentary"],
  );
  state = processTranscriptEvent(state, last);
  assert.deepEqual(
    state.items.filter((x) => x.type === "message").map((x) => x.text),
    ["Final answer"],
  );
  assert.equal(state.items[0].turnId, "canonical-turn");
  state = processTranscriptEvent(state, { ...first, seq: 4 });
  state = processTranscriptEvent(state, { ...last, seq: 5 });
  assert.deepEqual(
    state.items.filter((x) => x.type === "message").map((x) => x.text),
    ["Final answer"],
  );
  assert.deepEqual(
    state.items,
    buildTranscript([text(1, "Commentary"), first, last]),
  );
});

test("Hermes history is a separate restored view; active snapshots replace before live deltas", () => {
  const restored = text(1, "same", {
    kind: "history",
    operation: "replace",
    messageId: "history:31",
    turnId: undefined,
    part: 0,
    parts: 1,
  });
  const events = [
    restored,
    text(2, "same", {
      kind: "history",
      operation: "replace",
      messageId: "history:32",
      turnId: undefined,
      part: 0,
      parts: 1,
    }),
    text(3, "Working"),
    text(4, "Working now", {
      kind: "snapshot",
      operation: "replace",
      part: 0,
      parts: 1,
      replay: true,
    }),
    text(5, "."),
  ];
  const items = buildTranscript(events);
  assert.deepEqual(
    items.filter((x) => x.type === "message").map((x) => x.text),
    ["Working now."],
  );
  const history = items.filter((x) => x.type === "metadata");
  assert.equal(
    history.length,
    2,
    "identical text in different canonical history rows is legitimate",
  );
  assert.equal(history[0].title, "Restored history");
  assert.equal(
    history[0].turnId,
    null,
    "legacy history must not invent a turn",
  );
  assert.deepEqual(
    buildTranscript([...events, { ...restored, seq: 6 }]),
    items,
  );
});

test("Hermes tools retain partial fields with session and canonical-turn identity", () => {
  function tool(seq, turn, update, session = "session") {
    return {
      ...base,
      seq,
      payload: {
        method: "session/update",
        params: {
          sessionId: session,
          _meta: {
            kind: "live",
            operation: "merge",
            turnId: turn,
            messageId: `${turn}:tool:call`,
          },
          update,
        },
      },
    };
  }
  const start = {
    sessionUpdate: "tool_call",
    toolCallId: "call",
    title: "terminal",
    status: "in_progress",
    rawInput: { command: "sleep 10" },
  };
  const events = [
    tool(1, "first", start),
    tool(2, "second", start),
    tool(3, "first", {
      sessionUpdate: "tool_call_update",
      toolCallId: "call",
      rawOutput: "still working",
    }),
    tool(4, "first", {
      sessionUpdate: "tool_call_update",
      toolCallId: "call",
      status: "failed",
      rawOutput: "exit 1",
    }),
    tool(5, "first", start, "other-session"),
  ];
  const tools = buildTranscript(events).filter((x) => x.type === "tool");
  assert.equal(tools.length, 3);
  assert.deepEqual(
    tools.map((x) => x.turnId),
    ["first", "second", "first"],
  );
  assert.deepEqual(
    tools.map((x) => x.status),
    ["failed", "executing", "executing"],
  );
  assert.deepEqual(tools[0].args, { command: "sleep 10" });
  assert.equal(tools[0].result, "exit 1");
});

test("Hermes late ephemeral frames cannot overwrite an authoritative final", () => {
  const final = text(1, "Answer", {
    kind: "final",
    operation: "replace",
    part: 0,
    parts: 1,
    deliveryId: 17,
  });
  const done = receipt(2, { stopReason: "end_turn" });
  const items = buildTranscript([
    final,
    done,
    text(3, "late delta"),
    text(4, "old snapshot", {
      kind: "snapshot",
      operation: "replace",
      part: 0,
      parts: 1,
    }),
  ]);
  assert.deepEqual(
    items.filter((x) => x.type === "message").map((x) => x.text),
    ["Answer"],
  );
  const recovered = buildTranscript([
    text(1, "half", { kind: "final", operation: "replace", part: 0, parts: 2 }),
    done,
    { ...final, seq: 3 },
    { ...done, seq: 4 },
  ]);
  assert.equal(
    recovered.find((x) => x.type === "lifecycle").title,
    "Turn completed",
    "complete replay clears the incomplete-observation warning",
  );
});

test("Hermes admission retries show one prompt and ambiguous status stays visible", () => {
  const admit = {
    ...base,
    kind: "acp_write",
    seq: 1,
    payload: {
      method: "_hermes/turn/admit",
      params: {
        sessionId: "session",
        admissionId: "event-id",
        prompt: [
          { type: "text", text: "[Buzz event: @mention]\nContent: work" },
        ],
      },
    },
  };
  const status = {
    ...base,
    seq: 3,
    payload: {
      id: 9,
      result: {
        sessionId: "session",
        admissionId: "event-id",
        turnId: "canonical-turn",
        status: "unknown",
        error: "owner_restarted: outcome ambiguous; do not resubmit",
      },
    },
  };
  const items = buildTranscript([
    admit,
    { ...admit, seq: 2, turnId: "retry-turn" },
    status,
  ]);
  const prompts = items.filter(
    (x) => x.type === "message" && x.role === "user",
  );
  assert.equal(prompts.length, 1);
  assert.equal(prompts[0].text, "work");
  assert.ok(
    items.some(
      (x) => x.renderClass === "error" && /do not resubmit/.test(x.text),
    ),
  );
});

test("Hermes notices use delivery identity and recovery failures are visible", () => {
  const notice = (id) => ({
    ...base,
    seq: id,
    payload: {
      method: "session/update",
      params: {
        sessionId: "session",
        _meta: { deliveryId: id, replay: true },
        update: {
          sessionUpdate: "agent_message_chunk",
          content: { type: "text", text: "Notice" },
        },
      },
    },
  });
  const items = buildTranscript([
    notice(17),
    notice(18),
    { ...notice(17), seq: 19 },
    {
      ...base,
      seq: 20,
      payload: {
        id: 7,
        result: {
          _meta: {
            activeTurn: { turnId: "canonical-turn", snapshotTruncated: true },
            historyTruncated: true,
          },
        },
      },
    },
    {
      ...base,
      seq: 21,
      payload: {
        id: 8,
        error: {
          code: -32000,
          message: "replay_gap: cursor precedes retention floor",
        },
      },
    },
    {
      ...base,
      seq: 22,
      payload: {
        id: 9,
        result: {
          sessionId: "session",
          admissionId: "event",
          status: "unknown",
          error: "owner_restarted: outcome ambiguous; do not resubmit",
        },
      },
    },
  ]);
  assert.deepEqual(
    items.filter((x) => x.acpSource === "hermes:notice").map((x) => x.text),
    ["Notice", "Notice"],
  );
  const warnings = items.filter(
    (x) => x.type === "lifecycle" && x.renderClass === "error",
  );
  assert.equal(warnings.length, 3);
  assert.match(warnings[0].text, /truncated/i);
  assert.match(warnings[1].text, /replay_gap/);
  assert.match(warnings[2].text, /do not resubmit/);
});

test("Hermes terminal receipts are correlated and replay idempotent; partial finals cannot certify success", () => {
  for (const [params, title] of [
    [{ stopReason: "end_turn" }, "Turn completed"],
    [{ stopReason: "cancelled" }, "Turn cancelled"],
    [{ error: "provider broke" }, "Turn error"],
  ]) {
    const done = receipt(2, params);
    const items = buildTranscript([
      text(1, "Final", {
        kind: "final",
        operation: "replace",
        part: 0,
        parts: 1,
        deliveryId: 17,
      }),
      done,
      { ...done, seq: 3 },
    ]);
    const lifecycle = items.filter((x) => x.type === "lifecycle");
    assert.equal(lifecycle.length, 1);
    assert.equal(lifecycle[0].title, title);
    assert.equal(lifecycle[0].turnId, "canonical-turn");
    assert.equal(lifecycle[0].sessionId, "session");
  }
  const incomplete = buildTranscript([
    text(1, "half", {
      kind: "final",
      operation: "replace",
      part: 0,
      parts: 2,
      deliveryId: 17,
    }),
    receipt(2, { stopReason: "end_turn" }),
  ]);
  assert.equal(incomplete.filter((x) => x.type === "message").length, 0);
  assert.match(incomplete[0].text, /incomplete/i);
  assert.equal(incomplete[0].renderClass, "error");
});
